local M = {}

function M.load(theme)
	return {
		Normal          = { fg = theme.fg, bg = theme.bg },
		NormalFloat     = { fg = theme.fg, bg = theme.bg },
		FloatBorder     = { fg = theme.fg_muted },
		Comment         = { fg = theme.fg_muted, italic = true },
		Type            = { fg = theme.type },
		Variable        = { fg = theme.fg },
		String          = { fg = theme.string },
		Function        = { fg = theme.function_name },
		PreProc         = { fg = theme.special },
		Special         = { fg = theme.special },
		Constant        = { fg = theme.constant },
		Identifier      = { fg = theme.fg_subtle },
		Keyword         = { fg = theme.keyword },
		MoreMsg         = { fg = theme.fg },
		LineNr          = { fg = theme.fg_muted },
		DiagnosticError = { fg = theme.error },
		DiagnosticWarn  = { fg = theme.entity },
		DiagnosticInfo  = { fg = theme.fg },
		DiagnosticHint  = { fg = theme.fg },
		Title           = { fg = theme.fg },
		Question        = { fg = theme.fg },
		Directory       = { fg = theme.string, bold = true },
		Statement       = { fg = theme.fg },
		Visual          = { fg = theme.highlight },
		Search          = { fg = theme.highlight, },
		CurSearch       = { fg = theme.highlight_strong, },
		IncSearch       = { fg = theme.highlight, },
		StatusLine      = { fg = theme.fg_subtle },
		StatusLineNC    = { fg = theme.fg_muted },
		ModeMsg         = { fg = theme.fg },
		CursorLine      = { fg = theme.fg, bg = theme.bg },
		CursorLineNr    = { fg = theme.fg_muted },
		TabLine         = { fg = theme.fg, bg = theme.bg },
		Added           = { fg = theme.fg },
		Cursor          = { fg = theme.fg },
		NonText         = { fg = theme.fg },
		SpecialKey      = { fg = theme.special },
		PmenuSbar       = { bg = theme.bg },
		PmenuSel        = { fg = theme.highlight_strong },
		PmenuThumb      = { bg = theme.bg },
		Pmenu           = { fg = theme.fg, bg = theme.bg },
		Operator        = { fg = theme.fg },
		Delimiter       = { fg = theme.fg },
		DiffAdd         = { bg = theme.diff_add },
		DiffDelete      = { bg = theme.diff_delete },
		EndOfBuffer     = { fg = theme.fg_muted },
		WinSeparator    = { fg = theme.fg_muted },
	}
end

return M
